version: '3'

services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379

  fake-google-backend:
    build: sample_company/backend
    ports:
      - "5001:5000"

  fake_facebook:
    build: sample_company/backend
    ports:
      - "5002:5000"

  fake_microsoft:
    build: sample_company/backend
    ports:
      - "5003:5000"
      