name: Build Docker image on tag

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push frontend
      uses: docker/build-push-action@v6
      with:
        context: job_tracker/frontend
        push: true
        tags: tridangcs/job-tracker-frontend:latest

    - name: Build and push backend
      uses: docker/build-push-action@v6
      with:
        context: job_tracker/backend
        push: true
        tags: tridangcs/job-tracker-backend:latest
